version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    ports:
      - "127.0.0.1:10100:9000"  # MinIO API
      - "127.0.0.1:10101:9001"  # MinIO Console (Web Interface)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:

